# Generated by Django 5.1.6 on 2025-02-25 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company', '0001_initial'),
        ('Departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('company', 'name')},
        ),
    ]
